events {
    worker_connections 1024;
}

http {
    
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    
    upstream springboot_backend {
        server app:8080;
    }

    # السيرفر الأساسي (HTTP)
    server {
        listen 80;
        server_name localhost;

        location / {
    
            limit_req zone=api_limit burst=5 nodelay;

    
            proxy_pass http://springboot_backend;
            
    
            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
        }
    }
}